insert into cad_clientes (codigo, nome, cidade, uf) values (1,'Cliente A',  'Rio Branco','AC');
insert into cad_clientes (codigo, nome, cidade, uf) values (2,'Cliente B',  'Maceió','AL');
insert into cad_clientes (codigo, nome, cidade, uf) values (3,'Cliente C',  'Macapá','AP');
insert into cad_clientes (codigo, nome, cidade, uf) values (4,'Cliente D',  'Manaus','AM');
insert into cad_clientes (codigo, nome, cidade, uf) values (5,'Cliente E',  'Salvador','BA');
insert into cad_clientes (codigo, nome, cidade, uf) values (6,'Cliente F',  'Fortaleza','CE');
insert into cad_clientes (codigo, nome, cidade, uf) values (7,'Cliente G',  'Brasília','DF');
insert into cad_clientes (codigo, nome, cidade, uf) values (8,'Cliente H',  'Vitória','ES');
insert into cad_clientes (codigo, nome, cidade, uf) values (9,'Cliente I',  'Goiânia','GO');
insert into cad_clientes (codigo, nome, cidade, uf) values (10,'Cliente J', 'São Luís','MA');
insert into cad_clientes (codigo, nome, cidade, uf) values (11,'Cliente K', 'Cuiabá','MT');
insert into cad_clientes (codigo, nome, cidade, uf) values (12,'Cliente L', 'Campo Grande','MS');
insert into cad_clientes (codigo, nome, cidade, uf) values (13,'Cliente M', 'Belo Horizonte','MG');
insert into cad_clientes (codigo, nome, cidade, uf) values (14,'Cliente N', 'Belém','PA');
insert into cad_clientes (codigo, nome, cidade, uf) values (15,'Cliente O', 'João Pessoa','PB');
insert into cad_clientes (codigo, nome, cidade, uf) values (16,'Cliente P', 'Curitiba','PR');
insert into cad_clientes (codigo, nome, cidade, uf) values (17,'Cliente Q', 'Recife','PE');
insert into cad_clientes (codigo, nome, cidade, uf) values (18,'Cliente R', 'Teresina','PI');
insert into cad_clientes (codigo, nome, cidade, uf) values (19,'Cliente S', 'Rio de Janeiro','RJ');
insert into cad_clientes (codigo, nome, cidade, uf) values (20,'Cliente T', 'Natal','RN');
insert into cad_clientes (codigo, nome, cidade, uf) values (21,'Cliente U', 'Porto Alegre','RS');
insert into cad_clientes (codigo, nome, cidade, uf) values (22,'Cliente V', 'Porto Velho','RO');
insert into cad_clientes (codigo, nome, cidade, uf) values (23,'Cliente W', 'Boa Vista','RR');
insert into cad_clientes (codigo, nome, cidade, uf) values (24,'Cliente X', 'Florianópolis','SC');
insert into cad_clientes (codigo, nome, cidade, uf) values (25,'Cliente Y', 'São Paulo','SP');
insert into cad_clientes (codigo, nome, cidade, uf) values (26,'Cliente Z', 'Aracaju','SE');