insert into cad_produtos (codigo,descricao,preco_venda) values (1, 'Produto 001','0.10');
insert into cad_produtos (codigo,descricao,preco_venda) values (2, 'Produto 002','0.20');
insert into cad_produtos (codigo,descricao,preco_venda) values (3, 'Produto 003','0.30');
insert into cad_produtos (codigo,descricao,preco_venda) values (4, 'Produto 004','0.40');
insert into cad_produtos (codigo,descricao,preco_venda) values (5, 'Produto 005','0.50');
insert into cad_produtos (codigo,descricao,preco_venda) values (6, 'Produto 006','0.60');
insert into cad_produtos (codigo,descricao,preco_venda) values (7, 'Produto 007','0.70');
insert into cad_produtos (codigo,descricao,preco_venda) values (8, 'Produto 008','0.80');
insert into cad_produtos (codigo,descricao,preco_venda) values (9, 'Produto 009','0.90');
insert into cad_produtos (codigo,descricao,preco_venda) values (10,'Produto 010','1.00');
insert into cad_produtos (codigo,descricao,preco_venda) values (11,'Produto 011','1.10');
insert into cad_produtos (codigo,descricao,preco_venda) values (12,'Produto 012','1.20');
insert into cad_produtos (codigo,descricao,preco_venda) values (13,'Produto 013','1.30');
insert into cad_produtos (codigo,descricao,preco_venda) values (14,'Produto 014','1.40');
insert into cad_produtos (codigo,descricao,preco_venda) values (15,'Produto 015','1.50');
insert into cad_produtos (codigo,descricao,preco_venda) values (16,'Produto 016','1.60');
insert into cad_produtos (codigo,descricao,preco_venda) values (17,'Produto 017','1.70');
insert into cad_produtos (codigo,descricao,preco_venda) values (18,'Produto 018','1.80');
insert into cad_produtos (codigo,descricao,preco_venda) values (19,'Produto 019','1.90');
insert into cad_produtos (codigo,descricao,preco_venda) values (20,'Produto 020','2.00');
insert into cad_produtos (codigo,descricao,preco_venda) values (21,'Produto 021','2.10');
insert into cad_produtos (codigo,descricao,preco_venda) values (22,'Produto 022','2.20');
insert into cad_produtos (codigo,descricao,preco_venda) values (23,'Produto 023','2.30');
insert into cad_produtos (codigo,descricao,preco_venda) values (24,'Produto 024','2.40');
insert into cad_produtos (codigo,descricao,preco_venda) values (25,'Produto 025','2.50');
insert into cad_produtos (codigo,descricao,preco_venda) values (26,'Produto 026','2.60');
insert into cad_produtos (codigo,descricao,preco_venda) values (27,'Produto 027','2.70');
insert into cad_produtos (codigo,descricao,preco_venda) values (28,'Produto 028','2.80');
insert into cad_produtos (codigo,descricao,preco_venda) values (29,'Produto 029','2.90');
insert into cad_produtos (codigo,descricao,preco_venda) values (30,'Produto 030','3.00');
insert into cad_produtos (codigo,descricao,preco_venda) values (31,'Produto 031','3.10');
insert into cad_produtos (codigo,descricao,preco_venda) values (32,'Produto 032','3.20');
insert into cad_produtos (codigo,descricao,preco_venda) values (33,'Produto 033','3.30');
insert into cad_produtos (codigo,descricao,preco_venda) values (34,'Produto 034','3.40');
insert into cad_produtos (codigo,descricao,preco_venda) values (35,'Produto 035','3.50');
insert into cad_produtos (codigo,descricao,preco_venda) values (36,'Produto 036','3.60');
insert into cad_produtos (codigo,descricao,preco_venda) values (37,'Produto 037','3.70');
insert into cad_produtos (codigo,descricao,preco_venda) values (38,'Produto 038','3.80');
insert into cad_produtos (codigo,descricao,preco_venda) values (39,'Produto 039','3.90');
insert into cad_produtos (codigo,descricao,preco_venda) values (40,'Produto 040','4.00');
